# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
  Country.create( :iso_code => 'AF', :name => 'Afghanistan', :ioc_code => 'AFG')
  Country.create( :iso_code => 'AL', :name => 'Albania', :ioc_code => 'ALB')
  Country.create( :iso_code => 'DZ', :name => 'Algeria', :ioc_code => 'ALG')
  Country.create( :iso_code => 'AS', :name => 'American Samoa', :ioc_code => 'ASA')
  Country.create( :iso_code => 'AD', :name => 'Andorra', :ioc_code => 'AND')
  Country.create( :iso_code => 'AO', :name => 'Angola', :ioc_code => 'ANG')
  Country.create( :iso_code => 'AG', :name => 'Antigua and Barbuda', :ioc_code => 'ANT')
  Country.create( :iso_code => 'AR', :name => 'Argentina', :ioc_code => 'ARG')
  Country.create( :iso_code => 'AM', :name => 'Armenia', :ioc_code => 'ARM')
  Country.create( :iso_code => 'AW', :name => 'Aruba', :ioc_code => 'ARU')
  Country.create( :iso_code => 'AU', :name => 'Australia', :ioc_code => 'AUS')
  Country.create( :iso_code => 'AT', :name => 'Austria', :ioc_code => 'AUT')
  Country.create( :iso_code => 'AZ', :name => 'Azerbaijan', :ioc_code => 'AZE')
  Country.create( :iso_code => 'BS', :name => 'Bahamas', :ioc_code => 'BAH')
  Country.create( :iso_code => 'BH', :name => 'Bahrain', :ioc_code => 'BRN')
  Country.create( :iso_code => 'BD', :name => 'Bangladesh', :ioc_code => 'BAN')
  Country.create( :iso_code => 'BB', :name => 'Barbados', :ioc_code => 'BAR')
  Country.create( :iso_code => 'BY', :name => 'Belarus', :ioc_code => 'BLR')
  Country.create( :iso_code => 'BE', :name => 'Belgium', :ioc_code => 'BEL')
  Country.create( :iso_code => 'BZ', :name => 'Belize', :ioc_code => 'BIZ')
  Country.create( :iso_code => 'BJ', :name => 'Benin', :ioc_code => 'BEN')
  Country.create( :iso_code => 'BM', :name => 'Bermuda', :ioc_code => 'BER')
  Country.create( :iso_code => 'BT', :name => 'Bhutan', :ioc_code => 'BHU')
  Country.create( :iso_code => 'BO', :name => 'Bolivia', :ioc_code => 'BOL')
  Country.create( :iso_code => 'BA', :name => 'Bosnia and Herzegovina', :ioc_code => 'BIH')
  Country.create( :iso_code => 'BW', :name => 'Botswana', :ioc_code => 'BOT')
  Country.create( :iso_code => 'BR', :name => 'Brazil', :ioc_code => 'BRA')
  Country.create( :iso_code => 'BN', :name => 'Brunei Darussalam', :ioc_code => 'BRU')
  Country.create( :iso_code => 'BG', :name => 'Bulgaria', :ioc_code => 'BUL')
  Country.create( :iso_code => 'BF', :name => 'Burkina Faso', :ioc_code => 'BUR')
  Country.create( :iso_code => 'BI', :name => 'Burundi', :ioc_code => 'BDI')
  Country.create( :iso_code => 'KH', :name => 'Cambodia', :ioc_code => 'CAM')
  Country.create( :iso_code => 'CM', :name => 'Cameroon', :ioc_code => 'CMR')
  Country.create( :iso_code => 'CA', :name => 'Canada', :ioc_code => 'CAN')
  Country.create( :iso_code => 'CV', :name => 'Cape Verde', :ioc_code => 'CPV')
  Country.create( :iso_code => 'KY', :name => 'Cayman Islands', :ioc_code => 'CAY')
  Country.create( :iso_code => 'CF', :name => 'Central African Republic', :ioc_code => 'CAF')
  Country.create( :iso_code => 'TD', :name => 'Chad', :ioc_code => 'CHA')
  Country.create( :iso_code => 'CL', :name => 'Chile', :ioc_code => 'CHI')
  Country.create( :iso_code => 'CN', :name => 'China', :ioc_code => 'CHN')
  Country.create( :iso_code => 'CO', :name => 'Colombia', :ioc_code => 'COL')
  Country.create( :iso_code => 'KM', :name => 'Comoros', :ioc_code => 'COM')
  Country.create( :iso_code => 'CG', :name => 'Congo', :ioc_code => 'CGO')
  Country.create( :iso_code => 'CD', :name => 'Congo, Democratic Republic of the', :ioc_code => 'COD')
  Country.create( :iso_code => 'CK', :name => 'Cook Islands', :ioc_code => 'COK')
  Country.create( :iso_code => 'CR', :name => 'Costa Rica', :ioc_code => 'CRC')
  Country.create( :iso_code => 'CI', :name => 'Cote D\'Ivoire', :ioc_code => 'CIV')
  Country.create( :iso_code => 'HR', :name => 'Croatia', :ioc_code => 'CRO')
  Country.create( :iso_code => 'CU', :name => 'Cuba', :ioc_code => 'CUB')
  Country.create( :iso_code => 'CY', :name => 'Cyprus', :ioc_code => 'CYP')
  Country.create( :iso_code => 'CZ', :name => 'Czech Republic', :ioc_code => 'CZE')
  Country.create( :iso_code => 'DK', :name => 'Denmark', :ioc_code => 'DEN')
  Country.create( :iso_code => 'DJ', :name => 'Djibouti', :ioc_code => 'DJI')
  Country.create( :iso_code => 'DM', :name => 'Dominica', :ioc_code => 'DMA')
  Country.create( :iso_code => 'DO', :name => 'Dominican Republic', :ioc_code => 'DOM')
  Country.create( :iso_code => 'EC', :name => 'Ecuador', :ioc_code => 'ECU')
  Country.create( :iso_code => 'EG', :name => 'Egypt', :ioc_code => 'EGY')
  Country.create( :iso_code => 'SV', :name => 'El Salvador', :ioc_code => 'ESA')
  Country.create( :iso_code => 'GQ', :name => 'Equatorial Guinea', :ioc_code => 'GEQ')
  Country.create( :iso_code => 'ER', :name => 'Eritrea', :ioc_code => 'ERI')
  Country.create( :iso_code => 'EE', :name => 'Estonia', :ioc_code => 'EST')
  Country.create( :iso_code => 'ET', :name => 'Ethiopia', :ioc_code => 'ETH')
  Country.create( :iso_code => 'FJ', :name => 'Fiji', :ioc_code => 'FIJ')
  Country.create( :iso_code => 'FI', :name => 'Finland', :ioc_code => 'FIN')
  Country.create( :iso_code => 'FR', :name => 'France', :ioc_code => 'FRA')
  Country.create( :iso_code => 'GA', :name => 'Gabon', :ioc_code => 'GAB')
  Country.create( :iso_code => 'GM', :name => 'Gambia', :ioc_code => 'GAM')
  Country.create( :iso_code => 'GE', :name => 'Georgia', :ioc_code => 'GEO')
  Country.create( :iso_code => 'DE', :name => 'Germany', :ioc_code => 'GER')
  Country.create( :iso_code => 'GH', :name => 'Ghana', :ioc_code => 'GHA')
  Country.create( :iso_code => 'GR', :name => 'Greece', :ioc_code => 'GRE')
  Country.create( :iso_code => 'GD', :name => 'Grenada', :ioc_code => 'GRN')
  Country.create( :iso_code => 'GU', :name => 'Guam', :ioc_code => 'GUM')
  Country.create( :iso_code => 'GT', :name => 'Guatemala', :ioc_code => 'GUA')
  Country.create( :iso_code => 'GN', :name => 'Guinea', :ioc_code => 'GUI')
  Country.create( :iso_code => 'GW', :name => 'Guinea-Bissau', :ioc_code => 'GBS')
  Country.create( :iso_code => 'GY', :name => 'Guyana', :ioc_code => 'GUY')
  Country.create( :iso_code => 'HT', :name => 'Haiti', :ioc_code => 'HAI')
  Country.create( :iso_code => 'HN', :name => 'Honduras', :ioc_code => 'HON')
  Country.create( :iso_code => 'HK', :name => 'Hong Kong', :ioc_code => 'HKG')
  Country.create( :iso_code => 'HU', :name => 'Hungary', :ioc_code => 'HUN')
  Country.create( :iso_code => 'IS', :name => 'Iceland', :ioc_code => 'ISL')
  Country.create( :iso_code => 'IN', :name => 'India', :ioc_code => 'IND')
  Country.create( :iso_code => 'ID', :name => 'Indonesia', :ioc_code => 'INA')
  Country.create( :iso_code => 'IR', :name => 'Iran, Islamic Republic of', :ioc_code => 'IRI')
  Country.create( :iso_code => 'IQ', :name => 'Iraq', :ioc_code => 'IRQ')
  Country.create( :iso_code => 'IE', :name => 'Ireland', :ioc_code => 'IRL')
  Country.create( :iso_code => 'IL', :name => 'Israel', :ioc_code => 'ISR')
  Country.create( :iso_code => 'IT', :name => 'Italy', :ioc_code => 'ITA')
  Country.create( :iso_code => 'JM', :name => 'Jamaica', :ioc_code => 'JAM')
  Country.create( :iso_code => 'JP', :name => 'Japan', :ioc_code => 'JPN')
  Country.create( :iso_code => 'JO', :name => 'Jordan', :ioc_code => 'JOR')
  Country.create( :iso_code => 'KZ', :name => 'Kazakhstan', :ioc_code => 'KAZ')
  Country.create( :iso_code => 'KE', :name => 'Kenya', :ioc_code => 'KEN')
  Country.create( :iso_code => 'KP', :name => 'Korea, Democratic People\'s Republic of', :ioc_code => 'PRK')
  Country.create( :iso_code => 'KR', :name => 'Korea, Republic of', :ioc_code => 'KOR')
  Country.create( :iso_code => 'KW', :name => 'Kuwait', :ioc_code => 'KUW')
  Country.create( :iso_code => 'KG', :name => 'Kyrgyzstan', :ioc_code => 'KGZ')
  Country.create( :iso_code => 'LA', :name => 'Lao People\'s Democratic Republic', :ioc_code => 'LAO')
  Country.create( :iso_code => 'LV', :name => 'Latvia', :ioc_code => 'LAT')
  Country.create( :iso_code => 'LB', :name => 'Lebanon', :ioc_code => 'LIB')
  Country.create( :iso_code => 'LS', :name => 'Lesotho', :ioc_code => 'LES')
  Country.create( :iso_code => 'LR', :name => 'Liberia', :ioc_code => 'LBR')
  Country.create( :iso_code => 'LY', :name => 'Libyan Arab Jamahiriya', :ioc_code => 'LBA')
  Country.create( :iso_code => 'LI', :name => 'Liechtenstein', :ioc_code => 'LIE')
  Country.create( :iso_code => 'LT', :name => 'Lithuania', :ioc_code => 'LTU')
  Country.create( :iso_code => 'LU', :name => 'Luxembourg', :ioc_code => 'LUX')
  Country.create( :iso_code => 'MK', :name => 'Macedonia, Republic of', :ioc_code => 'MKD')
  Country.create( :iso_code => 'MG', :name => 'Madagascar', :ioc_code => 'MAD')
  Country.create( :iso_code => 'MW', :name => 'Malawi', :ioc_code => 'MAW')
  Country.create( :iso_code => 'MY', :name => 'Malaysia', :ioc_code => 'MAS')
  Country.create( :iso_code => 'MV', :name => 'Maldives', :ioc_code => 'MDV')
  Country.create( :iso_code => 'ML', :name => 'Mali', :ioc_code => 'MLI')
  Country.create( :iso_code => 'MT', :name => 'Malta', :ioc_code => 'MLT')
  Country.create( :iso_code => 'MR', :name => 'Mauritania', :ioc_code => 'MTN')
  Country.create( :iso_code => 'MU', :name => 'Mauritius', :ioc_code => 'MRI')
  Country.create( :iso_code => 'MX', :name => 'Mexico', :ioc_code => 'MEX')
  Country.create( :iso_code => 'FM', :name => 'Micronesia, Federated States of', :ioc_code => 'FSM')
  Country.create( :iso_code => 'MD', :name => 'Moldova, Republic of', :ioc_code => 'MDA')
  Country.create( :iso_code => 'MC', :name => 'Monaco', :ioc_code => 'MON')
  Country.create( :iso_code => 'MN', :name => 'Mongolia', :ioc_code => 'MGL')
  Country.create( :iso_code => 'MS', :name => 'Montserrat', :ioc_code => 'MAR')
  Country.create( :iso_code => 'MZ', :name => 'Mozambique', :ioc_code => 'MOZ')
  Country.create( :iso_code => 'MM', :name => 'Myanmar', :ioc_code => 'MYA')
  Country.create( :iso_code => 'NA', :name => 'Namibia', :ioc_code => 'NAM')
  Country.create( :iso_code => 'NR', :name => 'Nauru', :ioc_code => 'NRU')
  Country.create( :iso_code => 'NP', :name => 'Nepal', :ioc_code => 'NEP')
  Country.create( :iso_code => 'NL', :name => 'Netherlands', :ioc_code => 'NED')
  Country.create( :iso_code => 'AN', :name => 'Netherlands Antilles', :ioc_code => 'AHO')
  Country.create( :iso_code => 'NZ', :name => 'New Zealand', :ioc_code => 'NZL')
  Country.create( :iso_code => 'NI', :name => 'Nicaragua', :ioc_code => 'NCA')
  Country.create( :iso_code => 'NE', :name => 'Niger', :ioc_code => 'NIG')
  Country.create( :iso_code => 'NG', :name => 'Nigeria', :ioc_code => 'NGR')
  Country.create( :iso_code => 'NO', :name => 'Norway', :ioc_code => 'NOR')
  Country.create( :iso_code => 'OM', :name => 'Oman', :ioc_code => 'OMA')
  Country.create( :iso_code => 'PK', :name => 'Pakistan', :ioc_code => 'PAK')
  Country.create( :iso_code => 'PW', :name => 'Palau', :ioc_code => 'PLW')
  Country.create( :iso_code => 'PA', :name => 'Panama', :ioc_code => 'PAN')
  Country.create( :iso_code => 'PG', :name => 'Papua New Guinea', :ioc_code => 'PNG')
  Country.create( :iso_code => 'PY', :name => 'Paraguay', :ioc_code => 'PAR')
  Country.create( :iso_code => 'PE', :name => 'Peru', :ioc_code => 'PER')
  Country.create( :iso_code => 'PH', :name => 'Philippines', :ioc_code => 'PHI')
  Country.create( :iso_code => 'PL', :name => 'Poland', :ioc_code => 'POL')
  Country.create( :iso_code => 'PT', :name => 'Portugal', :ioc_code => 'POR')
  Country.create( :iso_code => 'PR', :name => 'Puerto Rico', :ioc_code => 'PUR')
  Country.create( :iso_code => 'QA', :name => 'Qatar', :ioc_code => 'QAT')
  Country.create( :iso_code => 'RO', :name => 'Romania', :ioc_code => 'ROM')
  Country.create( :iso_code => 'RU', :name => 'Russian Federation', :ioc_code => 'RUS')
  Country.create( :iso_code => 'RW', :name => 'Rwanda', :ioc_code => 'RWA')
  Country.create( :iso_code => 'KN', :name => 'Saint Kitts and Nevis', :ioc_code => 'SKN')
  Country.create( :iso_code => 'LC', :name => 'Saint Lucia', :ioc_code => 'LCA')
  Country.create( :iso_code => 'VC', :name => 'Saint Vincent and the Grenadines', :ioc_code => 'VIN')
  Country.create( :iso_code => 'WS', :name => 'Samoa', :ioc_code => 'SAM')
  Country.create( :iso_code => 'SM', :name => 'San Marino', :ioc_code => 'SMR')
  Country.create( :iso_code => 'ST', :name => 'Sao Tome and Principe', :ioc_code => 'STP')
  Country.create( :iso_code => 'SA', :name => 'Saudi Arabia', :ioc_code => 'KSA')
  Country.create( :iso_code => 'SN', :name => 'Senegal', :ioc_code => 'SEN')
  Country.create( :iso_code => 'RS', :name => 'Serbia, Republic of', :ioc_code => 'SCG')
  Country.create( :iso_code => 'SC', :name => 'Seychelles', :ioc_code => 'SEY')
  Country.create( :iso_code => 'SL', :name => 'Sierra Leone', :ioc_code => 'SLE')
  Country.create( :iso_code => 'SG', :name => 'Singapore', :ioc_code => 'SIN')
  Country.create( :iso_code => 'SK', :name => 'Slovakia', :ioc_code => 'SVK')
  Country.create( :iso_code => 'SI', :name => 'Slovenia', :ioc_code => 'SLO')
  Country.create( :iso_code => 'SB', :name => 'Solomon Islands', :ioc_code => 'SOL')
  Country.create( :iso_code => 'SO', :name => 'Somalia', :ioc_code => 'SOM')
  Country.create( :iso_code => 'ZA', :name => 'South Africa', :ioc_code => 'RSA')
  Country.create( :iso_code => 'ES', :name => 'Spain', :ioc_code => 'ESP')
  Country.create( :iso_code => 'LK', :name => 'Sri Lanka', :ioc_code => 'SRI')
  Country.create( :iso_code => 'SD', :name => 'Sudan', :ioc_code => 'SUD')
  Country.create( :iso_code => 'SR', :name => 'Suriname', :ioc_code => 'SUR')
  Country.create( :iso_code => 'SZ', :name => 'Swaziland', :ioc_code => 'SWZ')
  Country.create( :iso_code => 'SE', :name => 'Sweden', :ioc_code => 'SWE')
  Country.create( :iso_code => 'CH', :name => 'Switzerland', :ioc_code => 'SUI')
  Country.create( :iso_code => 'SY', :name => 'Syrian Arab Republic', :ioc_code => 'SYR')
  Country.create( :iso_code => 'TW', :name => 'Taiwan, Province of China', :ioc_code => 'TPE')
  Country.create( :iso_code => 'TJ', :name => 'Tajikistan', :ioc_code => 'TJK')
  Country.create( :iso_code => 'TZ', :name => 'Tanzania, United Republic of', :ioc_code => 'TAN')
  Country.create( :iso_code => 'TH', :name => 'Thailand', :ioc_code => 'THA')
  Country.create( :iso_code => 'TG', :name => 'Togo', :ioc_code => 'TOG')
  Country.create( :iso_code => 'TO', :name => 'Tonga', :ioc_code => 'TGA')
  Country.create( :iso_code => 'TT', :name => 'Trinidad and Tobago', :ioc_code => 'TRI')
  Country.create( :iso_code => 'TN', :name => 'Tunisia', :ioc_code => 'TUN')
  Country.create( :iso_code => 'TR', :name => 'Turkey', :ioc_code => 'TUR')
  Country.create( :iso_code => 'TM', :name => 'Turkmenistan', :ioc_code => 'TKM')
  Country.create( :iso_code => 'UG', :name => 'Uganda', :ioc_code => 'UGA')
  Country.create( :iso_code => 'UA', :name => 'Ukraine', :ioc_code => 'UKR')
  Country.create( :iso_code => 'AE', :name => 'United Arab Emirates', :ioc_code => 'UAE')
  Country.create( :iso_code => 'GB', :name => 'United Kingdom', :ioc_code => 'GBR')
  Country.create( :iso_code => 'US', :name => 'United States', :ioc_code => 'USA')
  Country.create( :iso_code => 'UY', :name => 'Uruguay', :ioc_code => 'URU')
  Country.create( :iso_code => 'UZ', :name => 'Uzbekistan', :ioc_code => 'UZB')
  Country.create( :iso_code => 'VU', :name => 'Vanuatu', :ioc_code => 'VAN')
  Country.create( :iso_code => 'VE', :name => 'Venezuela', :ioc_code => 'VEN')
  Country.create( :iso_code => 'VN', :name => 'Viet Nam', :ioc_code => 'VIE')
  Country.create( :iso_code => 'VG', :name => 'Virgin Islands, British', :ioc_code => 'IVB')
  Country.create( :iso_code => 'VI', :name => 'Virgin Islands U.S.', :ioc_code => 'ISV')
  Country.create( :iso_code => 'YE', :name => 'Yemen', :ioc_code => 'YEM')
  Country.create( :iso_code => 'ZM', :name => 'Zambia', :ioc_code => 'ZAM')
  Country.create( :iso_code => 'ZW', :name => 'Zimbabwe', :ioc_code => 'ZIM')

  Currency.create(:name => "Schweizer Franken", :iso_code => "CHF")
